// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/description-expense/{budget_uuid}": {
            "get": {
                "description": "Retrieves a collection of detailed expense transactions for a specific budget using its UUID. Supports pagination via limit and offset query parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expense"
                ],
                "summary": "Get a paginated list of individual expense transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent Budget UUID (36 characters)",
                        "name": "budget_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Maximum number of records to return (positive integer, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Number of records to skip (positive integer)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of expense transactions successfully retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/app_budget-planner_internal_model.DescriptionExpenses"
                                            }
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"limit\\\": \\\"the limit must be a positive integer not greater than 100\\\" } } or { \\\"errors\\\": { \\\"offset\\\": \\\"the offset must be a positive integer\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"expense\\\": \\\"not found description expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a detailed expense record and associates it with a specific budget by UUID. If the parent expense container does not exist, it initializes one automatically. Validates transaction category constraints and overall budget existence.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expense"
                ],
                "summary": "Create a new expense transaction under a budget",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent Budget UUID (36 characters)",
                        "name": "budget_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Expense creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_expense.RequestCreateDescriptionExpense"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Expense transaction successfully recorded",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_expense.ResponseCreateAndUpdateExpense"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"expense\\\": \\\"expense must be a positive decimals and greater than 0\\\" } } or { \\\"errors\\\": { \\\"category\\\": \\\"category mast be a health, sport, supermarket, restaurant, leisure, investments, savings or other\\\" } } or { \\\"errors\\\": { \\\"description\\\": \\\"description cannot be more than 250 characters\\\" } } or { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } } or { \\\"errors\\\": { \\\"body\\\": \\\"\u003craw_body_error\u003e\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to create expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/description-expense/{budget_uuid}/{description_expense_uuid}": {
            "get": {
                "description": "Retrieves the complete data of an individual expense transaction by its UUID under a specific budget. Validates the entity existence chain: parent budget, expense container, and the specific transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expense"
                ],
                "summary": "Get a specific expense transaction details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent Budget UUID (36 characters)",
                        "name": "budget_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Specific Transaction UUID (36 characters)",
                        "name": "description_expense_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Expense transaction details successfully retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_budget-planner_internal_model.DescriptionExpenses"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found expense\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found description expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a specific expense transaction record by its UUID under a parent budget. Recalculates total expense fields inside the database transaction and returns no content upon success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expense"
                ],
                "summary": "Delete an individual expense transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent Budget UUID (36 characters)",
                        "name": "budget_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Specific Transaction UUID (36 characters)",
                        "name": "description_expense_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Expense transaction successfully deleted, no content returned"
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found expense\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found description expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to delete expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates an individual expense transaction's category, expense amount, or description by its UUID under a specific budget. Validates the existence of the parent budget, the main expense container, and the specific transaction record.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expense"
                ],
                "summary": "Update an existing expense transaction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent Budget UUID (36 characters)",
                        "name": "budget_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Specific Transaction UUID (36 characters)",
                        "name": "description_expense_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Expense translation update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_expense.RequestUpdateDescriptionExpense"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Expense transaction successfully updated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_expense.ResponseCreateAndUpdateExpense"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"expense\\\": \\\"expense must be a positive decimals and greater than 0\\\" } } or { \\\"errors\\\": { \\\"category\\\": \\\"category mast be a health, sport, supermarket, restaurant, leisure, investments, savings or other\\\" } } or { \\\"errors\\\": { \\\"description\\\": \\\"description cannot be more than 250 characters\\\" } } or { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } } or { \\\"errors\\\": { \\\"body\\\": \\\"\u003craw_body_error\u003e\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found expense\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found description expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to update expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/expense/{budget_uuid}": {
            "get": {
                "description": "Retrieves the top-level aggregated expenses data (total spent vs budget limits) associated with a specific budget by its UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expense"
                ],
                "summary": "Get aggregated expenses for a specific budget",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Budget UUID (36 characters)",
                        "name": "budget_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aggregated expenses data successfully retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_budget-planner_internal_model.Expenses"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"expense\\\": \\\"not found expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/finance/{budget_uuid}/{expense_uuid}": {
            "get": {
                "description": "Calculates advanced financial analytics for a specific budget and expense container. Returns initial vs current balances, category-by-category expense tracking, percentage distribution, and a predicted average spend per day based on historical user data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "finance"
                ],
                "summary": "Get comprehensive financial analytics and predictive calculations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Budget UUID (36 characters)",
                        "name": "budget_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Expense Container UUID (36 characters)",
                        "name": "expense_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Comprehensive financial data successfully computed and retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_finance.Finance"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"the expense uuid must be exactly 36 characters\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } } or { \\\"errors\\\": { \\\"expense\\\": \\\"not found expense\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"finance\\\": \\\"failed to get finance\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/budget": {
            "get": {
                "description": "Retrieves a collection of budget plans for the authenticated user. Supports pagination via limit and offset query parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Get a paginated list of budget plans",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Maximum number of records to return (positive integer, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Number of records to skip (positive integer)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of budget plans successfully retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/app_budget-planner_internal_model.Budgets"
                                            }
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"limit\\\": \\\"the limit must be a positive integer not greater than 100\\\" } } or { \\\"errors\\\": { \\\"offset\\\": \\\"the offset must be a positive integer\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a personal budget allocation with date boundaries. Validates time period overlaps and restricts multiple active budgets for the same time window.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Create a new financial budget plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Budget creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_budget.RequestCreateBudget"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Budget plan successfully created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_budget-planner_internal_model.Budgets"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"amount\\\": \\\"amount must be a positive decimals and greater than 0\\\" } } or { \\\"errors\\\": { \\\"start\\\": \\\"the start parameter must be in the format YYYY-MM-DD\\\" } } or { \\\"errors\\\": { \\\"finish\\\": \\\"the finish parameter must be in the format YYYY-MM-DD\\\" } } or { \\\"errors\\\": { \\\"dates\\\": \\\"the start parameter cannot be greater than or equal to finish\\\" } } or { \\\"errors\\\": { \\\"dates\\\": \\\"the start and finish parameters are overlap with another budget time period\\\" } } or { \\\"errors\\\": { \\\"body\\\": \\\"\u003craw_body_error\u003e\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to create budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/budget/{uuid}": {
            "get": {
                "description": "Retrieves the complete data of a specific financial budget plan using its unique identifier. Validates resource ownership based on the extracted user token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Get budget plan details by UUID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Budget UUID (36 characters)",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Budget plan details successfully retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_budget-planner_internal_model.Budgets"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a budget by its UUID. Supports soft-delete (default) or hard-delete via query parameter. Validates budget existence and user ownership before execution.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Remove or hard delete a financial budget plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Budget UUID (36 characters)",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deletion type strategy: 'soft-delete' or 'hard-delete'. Defaults to soft-delete if empty.",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Budget successfully removed, no content returned"
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } } or { \\\"errors\\\": { \\\"type\\\": \\\"the type  must be a soft-delete or hard-delete\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to remove budget\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to delete budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates a budget's amount, dates, or description by its UUID. Validates that new date periods do not overlap with existing budgets and partial date updates are cross-checked with current values.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "budget"
                ],
                "summary": "Update an existing financial budget plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Budget UUID (36 characters)",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Budget partial update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_budget.RequestUpdateBudget"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Budget plan successfully updated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_budget-planner_internal_model.Budgets"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"amount\\\": \\\"amount must be a positive decimals and greater than 0\\\" } } or { \\\"errors\\\": { \\\"start\\\": \\\"the start parameter must be in the format YYYY-MM-DD\\\" } } or { \\\"errors\\\": { \\\"finish\\\": \\\"the finish parameter must be in the format YYYY-MM-DD\\\" } } or { \\\"errors\\\": { \\\"dates\\\": \\\"the start parameter cannot be greater than or equal to finish\\\" } } or { \\\"errors\\\": { \\\"dates\\\": \\\"the start and finish parameters are overlap with another budget time period\\\" } } or { \\\"errors\\\": { \\\"budget\\\": \\\"the budget uuid must be exactly 36 characters\\\" } } or { \\\"errors\\\": { \\\"body\\\": \\\"\u003craw_body_error\u003e\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"budget\\\": \\\"not found budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to update budget\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_budget-planner_internal_model.Budgets": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "budgetUUID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "finish": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userUUID": {
                    "type": "string"
                }
            }
        },
        "app_budget-planner_internal_model.DescriptionExpenses": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "descriptionExpenseUUID": {
                    "type": "string"
                },
                "expense": {
                    "type": "string"
                },
                "expenseUUID": {
                    "type": "string"
                }
            }
        },
        "app_budget-planner_internal_model.Expenses": {
            "type": "object",
            "properties": {
                "budgetUUID": {
                    "type": "string"
                },
                "expenseUUID": {
                    "type": "string"
                },
                "health": {
                    "type": "string"
                },
                "investments": {
                    "type": "string"
                },
                "leisure": {
                    "type": "string"
                },
                "other": {
                    "type": "string"
                },
                "restaurant": {
                    "type": "string"
                },
                "savings": {
                    "type": "string"
                },
                "sport": {
                    "type": "string"
                },
                "supermarket": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_budget.RequestCreateBudget": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finish": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "internal_budget.RequestUpdateBudget": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finish": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "internal_expense.RequestCreateDescriptionExpense": {
            "type": "object",
            "required": [
                "category",
                "expense"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "enum": [
                        "health",
                        "sport",
                        "supermarket",
                        "restaurant",
                        "leisure",
                        "investments",
                        "savings",
                        "other"
                    ]
                },
                "description": {
                    "type": "string",
                    "maxLength": 250
                },
                "expense": {
                    "type": "string"
                }
            }
        },
        "internal_expense.RequestUpdateDescriptionExpense": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "enum": [
                        "health",
                        "sport",
                        "supermarket",
                        "restaurant",
                        "leisure",
                        "investments",
                        "savings",
                        "other"
                    ]
                },
                "description": {
                    "type": "string",
                    "maxLength": 250
                },
                "expense": {
                    "type": "string"
                }
            }
        },
        "internal_expense.ResponseCreateAndUpdateExpense": {
            "type": "object",
            "properties": {
                "description_expenses": {
                    "$ref": "#/definitions/app_budget-planner_internal_model.DescriptionExpenses"
                },
                "expense": {
                    "$ref": "#/definitions/app_budget-planner_internal_model.Expenses"
                }
            }
        },
        "internal_finance.Budget": {
            "type": "object",
            "properties": {
                "budget_balance": {
                    "type": "string"
                },
                "budget_initial": {
                    "type": "string"
                },
                "predicted_average_spend_per_day": {
                    "type": "string"
                }
            }
        },
        "internal_finance.Expenses": {
            "type": "object",
            "properties": {
                "health": {
                    "type": "string"
                },
                "investments": {
                    "type": "string"
                },
                "leisure": {
                    "type": "string"
                },
                "other": {
                    "type": "string"
                },
                "restaurant": {
                    "type": "string"
                },
                "savings": {
                    "type": "string"
                },
                "sport": {
                    "type": "string"
                },
                "supermarket": {
                    "type": "string"
                }
            }
        },
        "internal_finance.ExpensesPercent": {
            "type": "object",
            "properties": {
                "health_expense_percent": {
                    "type": "string"
                },
                "investments_expense_percent": {
                    "type": "string"
                },
                "leisure_expense_percent": {
                    "type": "string"
                },
                "other_expense_percent": {
                    "type": "string"
                },
                "restaurant_expense_percent": {
                    "type": "string"
                },
                "savings_expense_percent": {
                    "type": "string"
                },
                "sport_expense_percent": {
                    "type": "string"
                },
                "supermarket_expense_percent": {
                    "type": "string"
                }
            }
        },
        "internal_finance.Finance": {
            "type": "object",
            "properties": {
                "budget": {
                    "$ref": "#/definitions/internal_finance.Budget"
                },
                "expenses": {
                    "$ref": "#/definitions/internal_finance.Expenses"
                },
                "expenses_percent": {
                    "$ref": "#/definitions/internal_finance.ExpensesPercent"
                }
            }
        },
        "response.NegativeResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Envelope budgeting, limit configurations, and category allocations",
            "name": "budget"
        },
        {
            "description": "Daily transaction tracking, merchant categorization, and historic expense logs",
            "name": "expense"
        },
        {
            "description": "Advanced predictive analytics, financial health scoring, and heavy data aggregation calculations",
            "name": "finance"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Budget Planner Microservice API",
	Description:      "Financial planning and management service. Provides personal budgeting, automated expense tracking, and advanced financial analytics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
