services:
  postgres:
    container_name: postgres-budget-planner
    image: postgres:latest
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - ${PATH_VOLUMES}/postgres-data:/var/lib/postgresql/18/data
  migration:
    container_name: migration-budget-planner
    build:
      context: ../../
      dockerfile: ./services/budget-planner-service/Dockerfile
    entrypoint: ["./migrator"]
    environment:
      DSN : ${DSN}
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
  app:
    container_name: app-budget-planner
    build:
      context: ../../
      dockerfile: ./services/budget-planner-service/Dockerfile
    ports:
        - "${EXTERNAL_API_PORT}:8080"
    environment:
      EXTERNAL_API_PORT : ${EXTERNAL_API_PORT}
      DSN : ${DSN}
    depends_on:
     migration:
       condition: service_completed_successfully

volumes:
  postgres-data:
