{{- range .Values.microservices }}
{{- $outside := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: default
spec:
  {{- $replicas := $.Values.replicasCount.defaultReplicas }}
  {{- if contains "user" .name }}
  {{- $replicas = $.Values.replicasCount.authReplicas }}
  {{- else if contains "budget-planner" .name }}
  {{- $replicas = $.Values.replicasCount.budgetReplicas }}
  {{- else if contains "notification" .name }}
  {{- $replicas = $.Values.replicasCount.notificationReplicas }}
  {{- else if contains "docs" .name }}
  {{- $replicas = $.Values.replicasCount.docsReplicas }}
  {{- end }}
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      annotations:
        timestamp: {{ now | date "20060102150405" | quote }}
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          {{- $version := $.Values.versions.defaultVersion }}
          {{- if contains "user" .name }}
          {{- $version = $.Values.versions.authUserVersion }}
          {{- else if contains "budget" .name }}
          {{- $version = $.Values.versions.budgetPlannerVersion }}
          {{- else if contains "notification" .name }}
          {{- $version = $.Values.versions.notificationVersion}}
          {{- else if contains "docs" .name }}
          {{- $version = $.Values.versions.gatewayDocsVersion}}
          {{- end }}
          image: "{{ .image }}:{{ $version }}"
          imagePullPolicy: Always
          {{- $port := 8080 }}
          {{- range $.Values.secrets }}
            {{- if eq .secretName $outside.secretName}}
            {{- range .envSecrets}}
            {{- if eq .name "EXTERNAL_API_PORT"}}
            {{- $port = .value}}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ $port }}
          env:
            {{- range $.Values.secrets }}
            {{- if eq .secretName $outside.secretName}}
            {{- range .envSecrets}}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $outside.secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- if .checkLivenessProbe }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $port }}
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ $port }}
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
            {{- end }}
---
{{- end }}