{{- range .Values.microservices }}
{{- $outside := . }}
{{- if .ingressPaths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  namespace: default
  {{- if $outside.isSecurityService}}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    {{- $realmName := ""}}
    {{- range $.Values.secrets }}
      {{- if eq .secretName $outside.secretName}}
      {{- range .envSecrets}}
      {{- if eq .name "REALM_NAME_AUTH"}}
      {{- $realmName = .value}}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
    nginx.ingress.kubernetes.io/auth-secret: {{ $outside.secretName| quote}}
    nginx.ingress.kubernetes.io/auth-realm: {{ $realmName | quote}}
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "10"
  {{- end}}
spec:
  ingressClassName: nginx
  rules:
     - http:
        paths:
          {{- range .ingressPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $outside.name }}-service
                {{- $port := 8080 }}
                {{- range $.Values.secrets }}
                  {{- if eq .secretName $outside.secretName}}
                  {{- range .envSecrets}}
                  {{- if eq .name "EXTERNAL_API_PORT"}}
                  {{- $port = .value}}
                  {{- end }}
                  {{- end }}
                  {{- end }}
                  {{- end }}
                port:
                  number: {{ $port }}
          {{- end }}
---
{{- end }}
{{- end }}