{{- range .Values.secrets }}
{{- if .envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: default
type: Opaque
stringData:
  {{- range .envSecrets }}
  {{ .key }}: {{ .value | quote }}
  {{- end }}
---
{{- end }}
{{- end }}