apiVersion: batch/v1
kind: Job
metadata:
  name: migration-user-job
spec:
  completions: 1
  backoffLimit: 2
  activeDeadlineSeconds: 200
  template:
    metadata:
      name: migration-user-pod
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: busybox:latest
          command:
            - "sh"
            - "-c"
            - "until nc -z -v -w3 postgres-user-headless 5432; do echo 'Waiting for PostgreSQL...'; sleep 2; done"
      containers:
        - name: migration-user-tool
          image: dmitriysyworov/auth-user-service:v1
          command: ["./migrator"]
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: auth-user-all-secrets
                  key: dsn